import type {
  AdminOverviewDto,
  DashboardDto,
  DebtItemDto,
  DebtSummaryDto,
  MembershipConversionSnapshotDto,
  NotificationItemDto,
  PaymentItemDto,
  ReportSummaryDto,
} from "@/lib/types/app";

export const demoDebts: DebtItemDto[] = [
  {
    id: "demo-card-1",
    name: "Tarjeta Visa principal",
    creditorName: "Banco Popular",
    type: "CREDIT_CARD",
    status: "CURRENT",
    currency: "DOP",
    currentBalance: 128000,
    creditLimit: 180000,
    effectiveBalance: 128000,
    interestRate: 49,
    interestRateType: "ANNUAL",
    interestRateMode: "VARIABLE",
    monthlyInterestEstimate: 5227,
    minimumPayment: 8600,
    paymentAmountType: "VARIABLE",
    statementDay: 8,
    dueDay: 22,
    nextDueDate: "2026-03-24T12:00:00.000Z",
    notificationsEnabled: true,
    lateFeeAmount: 0,
    extraChargesAmount: 0,
    utilizationPct: 71.1,
    notes: "Tarjeta principal usada para gastos recurrentes.",
    startedAt: "2025-02-01T12:00:00.000Z",
    estimatedEndAt: null,
    paidOffAt: null,
    archivedAt: null,
    createdAt: "2026-03-01T12:00:00.000Z",
    updatedAt: "2026-03-20T12:00:00.000Z",
    paymentCount: 4,
    totalPaid: 32000,
    lastPaymentAt: "2026-03-18T12:00:00.000Z",
    lastPaymentAmount: 8000,
  },
  {
    id: "demo-loan-1",
    name: "Préstamo personal",
    creditorName: "Asociación Cibao",
    type: "PERSONAL_LOAN",
    status: "CURRENT",
    currency: "DOP",
    currentBalance: 218000,
    creditLimit: null,
    effectiveBalance: 218000,
    interestRate: 22,
    interestRateType: "ANNUAL",
    interestRateMode: "FIXED",
    monthlyInterestEstimate: 3997,
    minimumPayment: 9800,
    paymentAmountType: "FIXED",
    statementDay: null,
    dueDay: 10,
    nextDueDate: "2026-03-28T12:00:00.000Z",
    notificationsEnabled: true,
    lateFeeAmount: 0,
    extraChargesAmount: 0,
    utilizationPct: null,
    notes: "Préstamo de consolidación parcial.",
    startedAt: "2025-01-15T12:00:00.000Z",
    estimatedEndAt: "2028-01-15T12:00:00.000Z",
    paidOffAt: null,
    archivedAt: null,
    createdAt: "2026-03-01T12:00:00.000Z",
    updatedAt: "2026-03-20T12:00:00.000Z",
    paymentCount: 2,
    totalPaid: 19600,
    lastPaymentAt: "2026-03-01T12:00:00.000Z",
    lastPaymentAmount: 9800,
  },
];

export const demoPayments: PaymentItemDto[] = [
  {
    id: "demo-payment-1",
    debtId: "demo-card-1",
    debtName: "Tarjeta Visa principal",
    amount: 8000,
    principalAmount: 4700,
    interestAmount: 3300,
    lateFeeAmount: 0,
    extraChargesAmount: 0,
    remainingBalanceAfter: 128000,
    source: "MANUAL",
    notes: "Pago del cierre de marzo.",
    paidAt: "2026-03-18T12:00:00.000Z",
    createdAt: "2026-03-18T12:00:00.000Z",
    updatedAt: "2026-03-18T12:00:00.000Z",
  },
  {
    id: "demo-payment-2",
    debtId: "demo-loan-1",
    debtName: "Préstamo personal",
    amount: 9800,
    principalAmount: 6100,
    interestAmount: 3700,
    lateFeeAmount: 0,
    extraChargesAmount: 0,
    remainingBalanceAfter: 218000,
    source: "MANUAL",
    notes: "Cuota mensual.",
    paidAt: "2026-03-01T12:00:00.000Z",
    createdAt: "2026-03-01T12:00:00.000Z",
    updatedAt: "2026-03-01T12:00:00.000Z",
  },
];

export const dashboardData: DashboardDto = {
  summary: {
    totalDebt: 346000,
    totalMinimumPayment: 18400,
    currentMonthlyBudget: 18400,
    monthlyIncome: 55000,
    monthlyEssentialExpensesTotal: 35000,
    monthlyDebtCapacity: 20000,
    estimatedMonthlyInterest: 9224,
    paidVsPendingPercentage: 14.7,
    projectedDebtFreeDate: "2027-03-01T12:00:00.000Z",
    recommendedDebtName: "Tarjeta Visa principal",
    recommendedDebtId: "demo-card-1",
    monthsToDebtFree: 12,
    interestSavings: 48200,
  },
  membership: {
    tier: "NORMAL",
    billingStatus: "ACTIVE",
    label: "Premium",
    guidanceLabel: "Salida rápida 6 meses",
    durationMonths: 6,
    monthlyPriceUsd: 5,
    recommendationUnlocked: true,
    description:
      "La opción premium enfocada en ayudarte a salir más rápido de tus deudas con una ruta guiada de 6 meses.",
    currentPeriodEnd: "2026-04-29T12:00:00.000Z",
    cancelAtPeriodEnd: false,
    billingConfigured: true,
  },
  analysisScope: {
    activeDebtCount: 2,
    analyzedDebtCount: 2,
    hiddenDebtCount: 0,
    partialAnalysis: false,
  },
  planComparison: {
    headline: "Plan recomendado: Avalancha",
    description:
      "El sistema comparó avalancha, bola de nieve e híbrido con tus deudas actuales para proponerte la salida más eficiente.",
    recommendedStrategy: "AVALANCHE",
    interestSavings: 48200,
    monthsSaved: 6,
    suggestedMonthlyBudget: 25000,
    inferredExtraPayment: 6600,
    assumption:
      "Para producir una mejora visible, el sistema simuló RD$6,600 extra al mes sobre el ritmo actual.",
    immediateAction:
      "Ataca primero Tarjeta Visa principal y envía el excedente mensual ahí.",
    currentPlan: {
      label: "Plan actual",
      strategy: "SNOWBALL",
      strategyLabel: "Bola de nieve",
      monthlyBudget: 18400,
      monthsToDebtFree: 18,
      projectedDebtFreeDate: "2027-09-01T12:00:00.000Z",
      totalInterest: 112400,
      totalPaid: 458400,
      remainingBalance: 0,
      feasible: true,
      reason: null,
    },
    optimizedPlan: {
      label: "Plan recomendado",
      strategy: "AVALANCHE",
      strategyLabel: "Avalancha",
      monthlyBudget: 25000,
      monthsToDebtFree: 12,
      projectedDebtFreeDate: "2027-03-01T12:00:00.000Z",
      totalInterest: 64200,
      totalPaid: 410200,
      remainingBalance: 0,
      feasible: true,
      reason: null,
    },
  },
  habitSignals: {
    weeklyStreak: 2,
    reviewPrompt: null,
    momentumMessage: "Vas mejor que el mes pasado.",
    microFeedback: "Buen movimiento, estás reduciendo intereses.",
  },
  upcomingTimeline: {
    headline: "Siempre a tiempo",
    support: "Tienes 2 fechas importantes esta semana.",
    items: [
      {
        debtId: "demo-card-1",
        debtName: "Tarjeta Visa principal",
        eventType: "STATEMENT_CLOSING",
        eventLabel: "Fecha de corte",
        occursOn: "2026-03-21T12:00:00.000Z",
        daysUntil: 3,
        summary: "Tarjeta Visa principal corta en 3 días.",
      },
      {
        debtId: "demo-loan-1",
        debtName: "Préstamo personal",
        eventType: "PAYMENT_DUE",
        eventLabel: "Fecha de pago",
        occursOn: "2026-03-23T12:00:00.000Z",
        daysUntil: 5,
        summary: "Préstamo personal vence en 5 días.",
      },
    ],
    emptyState: null,
  },
  debtBreakdown: [
    { label: "CREDIT_CARD", value: 128000 },
    { label: "PERSONAL_LOAN", value: 218000 },
  ],
  balanceHistory: [
    { label: "Oct 25", totalBalance: 412000 },
    { label: "Nov 25", totalBalance: 398000 },
    { label: "Dic 25", totalBalance: 386000 },
    { label: "Ene 26", totalBalance: 371000 },
    { label: "Feb 26", totalBalance: 359000 },
    { label: "Mar 26", totalBalance: 346000 },
  ],
  recentPayments: demoPayments,
  dueSoonDebts: demoDebts,
  urgentDebt: demoDebts[0] ?? null,
  recommendedOrder: [
    {
      id: "demo-card-1",
      name: "Tarjeta Visa principal",
      priorityRank: 1,
      score: 95,
      balance: 128000,
      monthlyRatePct: 4.08,
      explanation: "Sube al frente por tasa alta.",
    },
    {
      id: "demo-loan-1",
      name: "Préstamo personal",
      priorityRank: 2,
      score: 51,
      balance: 218000,
      monthlyRatePct: 1.83,
      explanation: "Queda segundo por tasa más baja.",
    },
  ],
  strategyExplanation:
    "Avalanche prioriza la deuda con mayor tasa para reducir intereses lo antes posible.",
  riskAlerts: [
    {
      title: "Pago mínimo riesgoso",
      description:
        "La tarjeta principal sigue demasiado cerca del interés del mes.",
    },
  ],
};

export const membershipConversionSnapshot: MembershipConversionSnapshotDto = {
  hasDebts: true,
  totalDebt: 346000,
  estimatedMonthlyInterest: 9224,
  monthlyIncome: 55000,
  monthlyEssentialExpensesTotal: 35000,
  monthlyDebtCapacity: 20000,
  currentMonthlyBudget: 18400,
  suggestedMonthlyBudget: 22000,
  inferredExtraPayment: 3600,
  currentMonthsToDebtFree: 31,
  optimizedMonthsToDebtFree: 24,
  currentDebtFreeDate: "2028-10-01T12:00:00.000Z",
  optimizedDebtFreeDate: "2028-03-01T12:00:00.000Z",
  interestSavings: 28650,
  monthsSaved: 7,
  recommendedStrategyLabel: "Avalancha",
  immediateAction:
    "Ataca primero Tarjeta Visa principal. Cubre los mínimos del resto y envía todo excedente a esa deuda.",
  urgentDebtName: "Tarjeta Visa principal",
  dueSoonCount: 2,
  riskAlertCount: 1,
};

export const debtSummary: DebtSummaryDto = {
  activeDebtCount: 2,
  archivedDebtCount: 0,
  totalBalance: 346000,
  totalMinimumPayment: 18400,
  totalMonthlyInterest: 9224,
  overdueCount: 0,
};

export const reportSummary: ReportSummaryDto = {
  from: "2026-03-01T00:00:00.000Z",
  to: "2026-03-31T23:59:59.999Z",
  totalPaid: 17800,
  totalPrincipalPaid: 10800,
  totalInterestPaid: 7000,
  totalFeesPaid: 0,
  paymentCount: 2,
  principalSharePct: 61,
  interestAndFeesSharePct: 39,
  progressSignal: "WATCH",
  coachingHeadline:
    "Tu avance existe, pero todavía se diluye más de lo ideal",
  coachingSummary:
    "Ya estás empujando capital, pero 39% de tu flujo sigue yéndose a intereses. Tarjeta Visa principal fue la deuda que más absorbió flujo.",
  recommendedNextStep:
    "Conviene concentrar más flujo en Tarjeta Visa principal para que el próximo período deje una mejor proporción a capital.",
  comparison: {
    signal: "IMPROVING",
    headline: "Tu flujo va mejor que en el período anterior",
    summary:
      "El porcentaje enviado a principal subió de 48% a 61% y el dinero absorbido por intereses/cargos bajó 13 puntos.",
    previousFrom: "2026-02-01T00:00:00.000Z",
    previousTo: "2026-02-28T23:59:59.999Z",
    previousPaymentCount: 2,
    previousPrincipalSharePct: 48,
    previousTotalPaid: 15400,
  },
  debtSummary: [
    {
      debtId: "demo-card-1",
      debtName: "Tarjeta Visa principal",
      totalPaid: 8000,
    },
    {
      debtId: "demo-loan-1",
      debtName: "Préstamo personal",
      totalPaid: 9800,
    },
  ],
  categorySummary: [
    { type: "CREDIT_CARD", totalPaid: 8000 },
    { type: "PERSONAL_LOAN", totalPaid: 9800 },
  ],
};

export const demoNotifications: NotificationItemDto[] = [
  {
    id: "notification-1",
    debtId: "demo-card-1",
    type: "DUE_SOON",
    channel: "IN_APP",
    severity: "WARNING",
    title: "Vence pronto: Tarjeta Visa principal",
    message:
      "Si cubres el mínimo antes del 24 de marzo, evitas presión adicional.",
    actionLabel: "Revisar deudas",
    actionHref: "/deudas",
    dueAt: "2026-03-24T12:00:00.000Z",
    readAt: null,
    sentAt: null,
    createdAt: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "notification-2",
    debtId: "demo-card-1",
    type: "STRATEGY_RECOMMENDATION",
    channel: "IN_APP",
    severity: "INFO",
    title: "Prioridad sugerida",
    message: "Avalanche recomienda atacar primero la tarjeta principal.",
    actionLabel: "Ver plan",
    actionHref: "/dashboard?focus=optimization",
    dueAt: null,
    readAt: "2026-03-20T13:00:00.000Z",
    sentAt: null,
    createdAt: "2026-03-20T12:30:00.000Z",
  },
  {
    id: "notification-3",
    debtId: null,
    type: "MONTHLY_REPORT",
    channel: "IN_APP",
    severity: "INFO",
    title: "Tu resumen mensual está listo",
    message:
      "Ya puedes revisar cuánto fue a principal, intereses y cargos en reportes.",
    actionLabel: "Abrir reportes",
    actionHref: "/reportes",
    dueAt: "2026-03-31T12:00:00.000Z",
    readAt: null,
    sentAt: null,
    createdAt: "2026-03-21T12:30:00.000Z",
  },
  {
    id: "notification-4",
    debtId: "demo-card-1",
    type: "STRATEGY_RECOMMENDATION",
    channel: "IN_APP",
    severity: "INFO",
    title: "Seguimiento premium de la semana",
    message:
      "Tarjeta Visa principal sigue como foco. Si sostienes RD$25,000 este mes, mantienes la ruta para salir en 12 meses.",
    actionLabel: "Ver plan",
    actionHref: "/dashboard?focus=optimization",
    dueAt: null,
    readAt: null,
    sentAt: null,
    createdAt: "2026-03-22T09:00:00.000Z",
  },
];

export const adminOverview: AdminOverviewDto = {
  totalUsers: 142,
  activeUsers: 137,
  disabledUsers: 5,
  totalDebts: 386,
  overdueDebts: 41,
  paymentCountLast30Days: 812,
  membershipSummary: {
    freeUsers: 96,
    premiumUsers: 31,
    proUsers: 15,
    activeBilling: 38,
    pendingBilling: 4,
    attentionBilling: 6,
  },
  reminderSummary: {
    emailReminderUsers: 57,
    monthlyReportUsers: 118,
  },
  emailTemplateSummary: {
    totalTemplates: 4,
    activeTemplates: 3,
    inactiveTemplates: 1,
  },
  users: [
    {
      id: "user-1",
      email: "demo@deudaclarard.com",
      firstName: "Carla",
      lastName: "Rodríguez",
      role: "USER",
      status: "ACTIVE",
      membershipTier: "NORMAL",
      membershipBillingStatus: "ACTIVE",
      createdAt: "2026-01-10T12:00:00.000Z",
      lastLoginAt: "2026-03-20T13:00:00.000Z",
      debtCount: 3,
    },
    {
      id: "user-2",
      email: "admin@deudaclarard.com",
      firstName: "Admin",
      lastName: "Sistema",
      role: "ADMIN",
      status: "ACTIVE",
      membershipTier: "FREE",
      membershipBillingStatus: "FREE",
      createdAt: "2026-01-01T12:00:00.000Z",
      lastLoginAt: "2026-03-20T11:00:00.000Z",
      debtCount: 0,
    },
  ],
  auditLogs: [
    {
      id: "audit-1",
      action: "LOGIN_SUCCESS",
      resourceType: "auth",
      resourceId: "user-1",
      createdAt: "2026-03-20T13:00:00.000Z",
      userEmail: "demo@deudaclarard.com",
      metadata: null,
    },
  ],
  emailTemplates: [
    {
      id: "template-1",
      key: "due-soon",
      name: "Vencimiento próximo",
      subject: "Tu deuda vence pronto",
      htmlContent: "<p>Hola {{name}}, tu deuda vence pronto.</p>",
      textContent: "Hola {{name}}, tu deuda vence pronto.",
      isActive: true,
      updatedAt: "2026-03-20T12:00:00.000Z",
    },
    {
      id: "template-2",
      key: "membership-activated",
      name: "Activación Premium",
      subject: "Tu plan Premium ya está activo",
      htmlContent: "<p>Tu plan Premium ya está activo.</p>",
      textContent: "Tu plan Premium ya está activo.",
      isActive: true,
      updatedAt: "2026-03-21T09:30:00.000Z",
    },
  ],
  recentDebts: [
    {
      id: "host-debt-1",
      name: "Tarjeta Visa principal",
      creditorName: "Banco Popular",
      userEmail: "demo@deudaclarard.com",
      status: "OVERDUE",
      effectiveBalance: 152340,
      nextDueDate: "2026-04-03T00:00:00.000Z",
      createdAt: "2026-03-21T14:00:00.000Z",
    },
    {
      id: "host-debt-2",
      name: "Préstamo personal",
      creditorName: "Asociación Cibao",
      userEmail: "carla@correo.com",
      status: "CURRENT",
      effectiveBalance: 284000,
      nextDueDate: "2026-04-11T00:00:00.000Z",
      createdAt: "2026-03-20T11:00:00.000Z",
    },
  ],
  recentPayments: [
    {
      id: "host-payment-1",
      debtName: "Tarjeta Visa principal",
      userEmail: "demo@deudaclarard.com",
      amount: 18500,
      source: "TRANSFER",
      paidAt: "2026-03-23T10:00:00.000Z",
      createdAt: "2026-03-23T10:05:00.000Z",
    },
    {
      id: "host-payment-2",
      debtName: "Préstamo personal",
      userEmail: "carla@correo.com",
      amount: 9200,
      source: "CARD",
      paidAt: "2026-03-22T08:00:00.000Z",
      createdAt: "2026-03-22T08:10:00.000Z",
    },
  ],
  recentNotifications: [
    {
      id: "host-notification-1",
      title: "Pago mínimo por vencer",
      type: "PAYMENT_DUE_SOON",
      severity: "HIGH",
      userEmail: "demo@deudaclarard.com",
      createdAt: "2026-03-23T07:30:00.000Z",
      sentAt: "2026-03-23T07:32:00.000Z",
      readAt: null,
    },
    {
      id: "host-notification-2",
      title: "Resumen mensual listo",
      type: "MONTHLY_REPORT",
      severity: "INFO",
      userEmail: "carla@correo.com",
      createdAt: "2026-03-22T06:00:00.000Z",
      sentAt: "2026-03-22T06:01:00.000Z",
      readAt: "2026-03-22T09:15:00.000Z",
    },
  ],
};
